// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.0
// source: pixiv_tailor.proto

package pixiv_tailor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_pixiv_tailor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_pixiv_tailor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ConfigModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigModule) Reset() {
	*x = ConfigModule{}
	mi := &file_pixiv_tailor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigModule) ProtoMessage() {}

func (x *ConfigModule) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigModule.ProtoReflect.Descriptor instead.
func (*ConfigModule) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigModule) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Config        *ConfigModule          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetConfigResponse) GetConfig() *ConfigModule {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConfigRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type ExportConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []string               `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportConfigRequest) Reset() {
	*x = ExportConfigRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportConfigRequest) ProtoMessage() {}

func (x *ExportConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportConfigRequest.ProtoReflect.Descriptor instead.
func (*ExportConfigRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{7}
}

func (x *ExportConfigRequest) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ExportConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ConfigData    string                 `protobuf:"bytes,2,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"` // JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportConfigResponse) Reset() {
	*x = ExportConfigResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportConfigResponse) ProtoMessage() {}

func (x *ExportConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportConfigResponse.ProtoReflect.Descriptor instead.
func (*ExportConfigResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{8}
}

func (x *ExportConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ExportConfigResponse) GetConfigData() string {
	if x != nil {
		return x.ConfigData
	}
	return ""
}

type ImportConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigData    string                 `protobuf:"bytes,1,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"` // JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportConfigRequest) Reset() {
	*x = ImportConfigRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportConfigRequest) ProtoMessage() {}

func (x *ImportConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportConfigRequest.ProtoReflect.Descriptor instead.
func (*ImportConfigRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{9}
}

func (x *ImportConfigRequest) GetConfigData() string {
	if x != nil {
		return x.ConfigData
	}
	return ""
}

type ImportConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportConfigResponse) Reset() {
	*x = ImportConfigResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportConfigResponse) ProtoMessage() {}

func (x *ImportConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportConfigResponse.ProtoReflect.Descriptor instead.
func (*ImportConfigResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{10}
}

func (x *ImportConfigResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Config        string                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"` // JSON 字符串
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pixiv_tailor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{11}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Task) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // JSON 字符串
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTaskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTaskRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTaskResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetTaskStatusResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{16}
}

func (x *ListTasksRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTasksRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{17}
}

func (x *ListTasksResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{18}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{19}
}

func (x *CancelTaskResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type TaskProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgressUpdate) Reset() {
	*x = TaskProgressUpdate{}
	mi := &file_pixiv_tailor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgressUpdate) ProtoMessage() {}

func (x *TaskProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgressUpdate.ProtoReflect.Descriptor instead.
func (*TaskProgressUpdate) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{20}
}

func (x *TaskProgressUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskProgressUpdate) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskProgressUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskProgressUpdate) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type GetTaskProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskProgressRequest) Reset() {
	*x = GetTaskProgressRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskProgressRequest) ProtoMessage() {}

func (x *GetTaskProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskProgressRequest.ProtoReflect.Descriptor instead.
func (*GetTaskProgressRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{21}
}

func (x *GetTaskProgressRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pixiv_tailor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{22}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type GetTaskLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskLogsRequest) Reset() {
	*x = GetTaskLogsRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskLogsRequest) ProtoMessage() {}

func (x *GetTaskLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskLogsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskLogsRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{23}
}

func (x *GetTaskLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CrawlResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlResult) Reset() {
	*x = CrawlResult{}
	mi := &file_pixiv_tailor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlResult) ProtoMessage() {}

func (x *CrawlResult) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlResult.ProtoReflect.Descriptor instead.
func (*CrawlResult) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{24}
}

func (x *CrawlResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrawlResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CrawlResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CrawlResult) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CrawlResult) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CrawlResult) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CrawlResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetCrawlResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCrawlResultsRequest) Reset() {
	*x = GetCrawlResultsRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrawlResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrawlResultsRequest) ProtoMessage() {}

func (x *GetCrawlResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrawlResultsRequest.ProtoReflect.Descriptor instead.
func (*GetCrawlResultsRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{25}
}

func (x *GetCrawlResultsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetCrawlResultsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetCrawlResultsRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type GetCrawlResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Results       []*CrawlResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCrawlResultsResponse) Reset() {
	*x = GetCrawlResultsResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrawlResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrawlResultsResponse) ProtoMessage() {}

func (x *GetCrawlResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrawlResultsResponse.ProtoReflect.Descriptor instead.
func (*GetCrawlResultsResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{26}
}

func (x *GetCrawlResultsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetCrawlResultsResponse) GetResults() []*CrawlResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetCrawlResultsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GeneratedImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedImage) Reset() {
	*x = GeneratedImage{}
	mi := &file_pixiv_tailor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedImage) ProtoMessage() {}

func (x *GeneratedImage) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedImage.ProtoReflect.Descriptor instead.
func (*GeneratedImage) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{27}
}

func (x *GeneratedImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GeneratedImage) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GeneratedImage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GeneratedImage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GeneratedImage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetGeneratedImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneratedImagesRequest) Reset() {
	*x = GetGeneratedImagesRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneratedImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneratedImagesRequest) ProtoMessage() {}

func (x *GetGeneratedImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneratedImagesRequest.ProtoReflect.Descriptor instead.
func (*GetGeneratedImagesRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{28}
}

func (x *GetGeneratedImagesRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetGeneratedImagesRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetGeneratedImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Images        []*GeneratedImage      `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeneratedImagesResponse) Reset() {
	*x = GetGeneratedImagesResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeneratedImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeneratedImagesResponse) ProtoMessage() {}

func (x *GetGeneratedImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeneratedImagesResponse.ProtoReflect.Descriptor instead.
func (*GetGeneratedImagesResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{29}
}

func (x *GetGeneratedImagesResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetGeneratedImagesResponse) GetImages() []*GeneratedImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GetGeneratedImagesResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type TrainedModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainedModel) Reset() {
	*x = TrainedModel{}
	mi := &file_pixiv_tailor_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainedModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainedModel) ProtoMessage() {}

func (x *TrainedModel) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainedModel.ProtoReflect.Descriptor instead.
func (*TrainedModel) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{30}
}

func (x *TrainedModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrainedModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainedModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TrainedModel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TrainedModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetTrainedModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainedModelsRequest) Reset() {
	*x = GetTrainedModelsRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainedModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainedModelsRequest) ProtoMessage() {}

func (x *GetTrainedModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainedModelsRequest.ProtoReflect.Descriptor instead.
func (*GetTrainedModelsRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{31}
}

func (x *GetTrainedModelsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTrainedModelsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetTrainedModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Models        []*TrainedModel        `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrainedModelsResponse) Reset() {
	*x = GetTrainedModelsResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrainedModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainedModelsResponse) ProtoMessage() {}

func (x *GetTrainedModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainedModelsResponse.ProtoReflect.Descriptor instead.
func (*GetTrainedModelsResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{32}
}

func (x *GetTrainedModelsResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetTrainedModelsResponse) GetModels() []*TrainedModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *GetTrainedModelsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SystemInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Uptime            string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Memory            *MemoryInfo            `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu               *CPUInfo               `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Disk              *DiskInfo              `protobuf:"bytes,6,opt,name=disk,proto3" json:"disk,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,7,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	Warnings          []string               `protobuf:"bytes,8,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_pixiv_tailor_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{33}
}

func (x *SystemInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SystemInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SystemInfo) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *SystemInfo) GetMemory() *MemoryInfo {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemInfo) GetCpu() *CPUInfo {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemInfo) GetDisk() *DiskInfo {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *SystemInfo) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *SystemInfo) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type MemoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Used          int64                  `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Usage         int32                  `protobuf:"varint,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Available     int64                  `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_pixiv_tailor_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{34}
}

func (x *MemoryInfo) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryInfo) GetUsage() int32 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *MemoryInfo) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type CPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         int32                  `protobuf:"varint,1,opt,name=usage,proto3" json:"usage,omitempty"`
	Average       int32                  `protobuf:"varint,2,opt,name=average,proto3" json:"average,omitempty"`
	Peak          int32                  `protobuf:"varint,3,opt,name=peak,proto3" json:"peak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUInfo) Reset() {
	*x = CPUInfo{}
	mi := &file_pixiv_tailor_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUInfo) ProtoMessage() {}

func (x *CPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUInfo.ProtoReflect.Descriptor instead.
func (*CPUInfo) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{35}
}

func (x *CPUInfo) GetUsage() int32 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *CPUInfo) GetAverage() int32 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *CPUInfo) GetPeak() int32 {
	if x != nil {
		return x.Peak
	}
	return 0
}

type DiskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int64                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	DataUsed      int64                  `protobuf:"varint,2,opt,name=data_used,json=dataUsed,proto3" json:"data_used,omitempty"`
	DataTotal     int64                  `protobuf:"varint,3,opt,name=data_total,json=dataTotal,proto3" json:"data_total,omitempty"`
	Models        int64                  `protobuf:"varint,4,opt,name=models,proto3" json:"models,omitempty"`
	ModelsUsed    int64                  `protobuf:"varint,5,opt,name=models_used,json=modelsUsed,proto3" json:"models_used,omitempty"`
	ModelsTotal   int64                  `protobuf:"varint,6,opt,name=models_total,json=modelsTotal,proto3" json:"models_total,omitempty"`
	Logs          int64                  `protobuf:"varint,7,opt,name=logs,proto3" json:"logs,omitempty"`
	LogsUsed      int64                  `protobuf:"varint,8,opt,name=logs_used,json=logsUsed,proto3" json:"logs_used,omitempty"`
	LogsTotal     int64                  `protobuf:"varint,9,opt,name=logs_total,json=logsTotal,proto3" json:"logs_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_pixiv_tailor_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{36}
}

func (x *DiskInfo) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *DiskInfo) GetDataUsed() int64 {
	if x != nil {
		return x.DataUsed
	}
	return 0
}

func (x *DiskInfo) GetDataTotal() int64 {
	if x != nil {
		return x.DataTotal
	}
	return 0
}

func (x *DiskInfo) GetModels() int64 {
	if x != nil {
		return x.Models
	}
	return 0
}

func (x *DiskInfo) GetModelsUsed() int64 {
	if x != nil {
		return x.ModelsUsed
	}
	return 0
}

func (x *DiskInfo) GetModelsTotal() int64 {
	if x != nil {
		return x.ModelsTotal
	}
	return 0
}

func (x *DiskInfo) GetLogs() int64 {
	if x != nil {
		return x.Logs
	}
	return 0
}

func (x *DiskInfo) GetLogsUsed() int64 {
	if x != nil {
		return x.LogsUsed
	}
	return 0
}

func (x *DiskInfo) GetLogsTotal() int64 {
	if x != nil {
		return x.LogsTotal
	}
	return 0
}

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_pixiv_tailor_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{37}
}

type GetSystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SystemInfo    *SystemInfo            `protobuf:"bytes,2,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_pixiv_tailor_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pixiv_tailor_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_pixiv_tailor_proto_rawDescGZIP(), []int{38}
}

func (x *GetSystemInfoResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetSystemInfoResponse) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

var File_pixiv_tailor_proto protoreflect.FileDescriptor

const file_pixiv_tailor_proto_rawDesc = "" +
	"\n" +
	"\x12pixiv_tailor.proto\x12\fpixiv_tailor\"P\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"S\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\":\n" +
	"\fConfigModule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"*\n" +
	"\x10GetConfigRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\"u\n" +
	"\x11GetConfigResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x122\n" +
	"\x06config\x18\x02 \x01(\v2\x1a.pixiv_tailor.ConfigModuleR\x06config\"E\n" +
	"\x13UpdateConfigRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"D\n" +
	"\x14UpdateConfigResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\"/\n" +
	"\x13ExportConfigRequest\x12\x18\n" +
	"\amodules\x18\x01 \x03(\tR\amodules\"e\n" +
	"\x14ExportConfigResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x12\x1f\n" +
	"\vconfig_data\x18\x02 \x01(\tR\n" +
	"configData\"6\n" +
	"\x13ImportConfigRequest\x12\x1f\n" +
	"\vconfig_data\x18\x01 \x01(\tR\n" +
	"configData\"D\n" +
	"\x14ImportConfigResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\"\xbd\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"?\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"j\n" +
	"\x12CreateTaskResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x12&\n" +
	"\x04task\x18\x02 \x01(\v2\x12.pixiv_tailor.TaskR\x04task\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"m\n" +
	"\x15GetTaskStatusResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x12&\n" +
	"\x04task\x18\x02 \x01(\v2\x12.pixiv_tailor.TaskR\x04task\"x\n" +
	"\x10ListTasksRequest\x128\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xa5\x01\n" +
	"\x11ListTasksResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x12(\n" +
	"\x05tasks\x18\x02 \x03(\v2\x12.pixiv_tailor.TaskR\x05tasks\x128\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"B\n" +
	"\x12CancelTaskResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\"\x95\x01\n" +
	"\x12TaskProgressUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\"1\n" +
	"\x16GetTaskProgressRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"r\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"C\n" +
	"\x12GetTaskLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xad\x01\n" +
	"\vCrawlResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"~\n" +
	"\x16GetCrawlResultsRequest\x128\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\"\xb6\x01\n" +
	"\x17GetCrawlResultsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x123\n" +
	"\aresults\x18\x02 \x03(\v2\x19.pixiv_tailor.CrawlResultR\aresults\x128\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\"\x8a\x01\n" +
	"\x0eGeneratedImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"k\n" +
	"\x19GetGeneratedImagesRequest\x128\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"\xba\x01\n" +
	"\x1aGetGeneratedImagesResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x124\n" +
	"\x06images\x18\x02 \x03(\v2\x1c.pixiv_tailor.GeneratedImageR\x06images\x128\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\"y\n" +
	"\fTrainedModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"g\n" +
	"\x17GetTrainedModelsRequest\x128\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xb6\x01\n" +
	"\x18GetTrainedModelsResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x122\n" +
	"\x06models\x18\x02 \x03(\v2\x1a.pixiv_tailor.TrainedModelR\x06models\x128\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x18.pixiv_tailor.PaginationR\n" +
	"pagination\"\xa8\x02\n" +
	"\n" +
	"SystemInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\x120\n" +
	"\x06memory\x18\x04 \x01(\v2\x18.pixiv_tailor.MemoryInfoR\x06memory\x12'\n" +
	"\x03cpu\x18\x05 \x01(\v2\x15.pixiv_tailor.CPUInfoR\x03cpu\x12*\n" +
	"\x04disk\x18\x06 \x01(\v2\x16.pixiv_tailor.DiskInfoR\x04disk\x12-\n" +
	"\x12active_connections\x18\a \x01(\x05R\x11activeConnections\x12\x1a\n" +
	"\bwarnings\x18\b \x03(\tR\bwarnings\"j\n" +
	"\n" +
	"MemoryInfo\x12\x12\n" +
	"\x04used\x18\x01 \x01(\x03R\x04used\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05usage\x18\x03 \x01(\x05R\x05usage\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\x03R\tavailable\"M\n" +
	"\aCPUInfo\x12\x14\n" +
	"\x05usage\x18\x01 \x01(\x05R\x05usage\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x05R\aaverage\x12\x12\n" +
	"\x04peak\x18\x03 \x01(\x05R\x04peak\"\x86\x02\n" +
	"\bDiskInfo\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x03R\x04data\x12\x1b\n" +
	"\tdata_used\x18\x02 \x01(\x03R\bdataUsed\x12\x1d\n" +
	"\n" +
	"data_total\x18\x03 \x01(\x03R\tdataTotal\x12\x16\n" +
	"\x06models\x18\x04 \x01(\x03R\x06models\x12\x1f\n" +
	"\vmodels_used\x18\x05 \x01(\x03R\n" +
	"modelsUsed\x12!\n" +
	"\fmodels_total\x18\x06 \x01(\x03R\vmodelsTotal\x12\x12\n" +
	"\x04logs\x18\a \x01(\x03R\x04logs\x12\x1b\n" +
	"\tlogs_used\x18\b \x01(\x03R\blogsUsed\x12\x1d\n" +
	"\n" +
	"logs_total\x18\t \x01(\x03R\tlogsTotal\"\x16\n" +
	"\x14GetSystemInfoRequest\"\x80\x01\n" +
	"\x15GetSystemInfoResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.pixiv_tailor.StatusR\x06status\x129\n" +
	"\vsystem_info\x18\x02 \x01(\v2\x18.pixiv_tailor.SystemInfoR\n" +
	"systemInfo2\xdf\t\n" +
	"\x12PixivTailorService\x12L\n" +
	"\tGetConfig\x12\x1e.pixiv_tailor.GetConfigRequest\x1a\x1f.pixiv_tailor.GetConfigResponse\x12U\n" +
	"\fUpdateConfig\x12!.pixiv_tailor.UpdateConfigRequest\x1a\".pixiv_tailor.UpdateConfigResponse\x12U\n" +
	"\fExportConfig\x12!.pixiv_tailor.ExportConfigRequest\x1a\".pixiv_tailor.ExportConfigResponse\x12U\n" +
	"\fImportConfig\x12!.pixiv_tailor.ImportConfigRequest\x1a\".pixiv_tailor.ImportConfigResponse\x12O\n" +
	"\n" +
	"CreateTask\x12\x1f.pixiv_tailor.CreateTaskRequest\x1a .pixiv_tailor.CreateTaskResponse\x12X\n" +
	"\rGetTaskStatus\x12\".pixiv_tailor.GetTaskStatusRequest\x1a#.pixiv_tailor.GetTaskStatusResponse\x12L\n" +
	"\tListTasks\x12\x1e.pixiv_tailor.ListTasksRequest\x1a\x1f.pixiv_tailor.ListTasksResponse\x12O\n" +
	"\n" +
	"CancelTask\x12\x1f.pixiv_tailor.CancelTaskRequest\x1a .pixiv_tailor.CancelTaskResponse\x12[\n" +
	"\x0fGetTaskProgress\x12$.pixiv_tailor.GetTaskProgressRequest\x1a .pixiv_tailor.TaskProgressUpdate0\x01\x12I\n" +
	"\vGetTaskLogs\x12 .pixiv_tailor.GetTaskLogsRequest\x1a\x16.pixiv_tailor.LogEntry0\x01\x12^\n" +
	"\x0fGetCrawlResults\x12$.pixiv_tailor.GetCrawlResultsRequest\x1a%.pixiv_tailor.GetCrawlResultsResponse\x12g\n" +
	"\x12GetGeneratedImages\x12'.pixiv_tailor.GetGeneratedImagesRequest\x1a(.pixiv_tailor.GetGeneratedImagesResponse\x12a\n" +
	"\x10GetTrainedModels\x12%.pixiv_tailor.GetTrainedModelsRequest\x1a&.pixiv_tailor.GetTrainedModelsResponse\x12X\n" +
	"\rGetSystemInfo\x12\".pixiv_tailor.GetSystemInfoRequest\x1a#.pixiv_tailor.GetSystemInfoResponseB!Z\x1fpixiv-tailor/proto/pixiv_tailorb\x06proto3"

var (
	file_pixiv_tailor_proto_rawDescOnce sync.Once
	file_pixiv_tailor_proto_rawDescData []byte
)

func file_pixiv_tailor_proto_rawDescGZIP() []byte {
	file_pixiv_tailor_proto_rawDescOnce.Do(func() {
		file_pixiv_tailor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pixiv_tailor_proto_rawDesc), len(file_pixiv_tailor_proto_rawDesc)))
	})
	return file_pixiv_tailor_proto_rawDescData
}

var file_pixiv_tailor_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_pixiv_tailor_proto_goTypes = []any{
	(*Status)(nil),                     // 0: pixiv_tailor.Status
	(*Pagination)(nil),                 // 1: pixiv_tailor.Pagination
	(*ConfigModule)(nil),               // 2: pixiv_tailor.ConfigModule
	(*GetConfigRequest)(nil),           // 3: pixiv_tailor.GetConfigRequest
	(*GetConfigResponse)(nil),          // 4: pixiv_tailor.GetConfigResponse
	(*UpdateConfigRequest)(nil),        // 5: pixiv_tailor.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),       // 6: pixiv_tailor.UpdateConfigResponse
	(*ExportConfigRequest)(nil),        // 7: pixiv_tailor.ExportConfigRequest
	(*ExportConfigResponse)(nil),       // 8: pixiv_tailor.ExportConfigResponse
	(*ImportConfigRequest)(nil),        // 9: pixiv_tailor.ImportConfigRequest
	(*ImportConfigResponse)(nil),       // 10: pixiv_tailor.ImportConfigResponse
	(*Task)(nil),                       // 11: pixiv_tailor.Task
	(*CreateTaskRequest)(nil),          // 12: pixiv_tailor.CreateTaskRequest
	(*CreateTaskResponse)(nil),         // 13: pixiv_tailor.CreateTaskResponse
	(*GetTaskStatusRequest)(nil),       // 14: pixiv_tailor.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil),      // 15: pixiv_tailor.GetTaskStatusResponse
	(*ListTasksRequest)(nil),           // 16: pixiv_tailor.ListTasksRequest
	(*ListTasksResponse)(nil),          // 17: pixiv_tailor.ListTasksResponse
	(*CancelTaskRequest)(nil),          // 18: pixiv_tailor.CancelTaskRequest
	(*CancelTaskResponse)(nil),         // 19: pixiv_tailor.CancelTaskResponse
	(*TaskProgressUpdate)(nil),         // 20: pixiv_tailor.TaskProgressUpdate
	(*GetTaskProgressRequest)(nil),     // 21: pixiv_tailor.GetTaskProgressRequest
	(*LogEntry)(nil),                   // 22: pixiv_tailor.LogEntry
	(*GetTaskLogsRequest)(nil),         // 23: pixiv_tailor.GetTaskLogsRequest
	(*CrawlResult)(nil),                // 24: pixiv_tailor.CrawlResult
	(*GetCrawlResultsRequest)(nil),     // 25: pixiv_tailor.GetCrawlResultsRequest
	(*GetCrawlResultsResponse)(nil),    // 26: pixiv_tailor.GetCrawlResultsResponse
	(*GeneratedImage)(nil),             // 27: pixiv_tailor.GeneratedImage
	(*GetGeneratedImagesRequest)(nil),  // 28: pixiv_tailor.GetGeneratedImagesRequest
	(*GetGeneratedImagesResponse)(nil), // 29: pixiv_tailor.GetGeneratedImagesResponse
	(*TrainedModel)(nil),               // 30: pixiv_tailor.TrainedModel
	(*GetTrainedModelsRequest)(nil),    // 31: pixiv_tailor.GetTrainedModelsRequest
	(*GetTrainedModelsResponse)(nil),   // 32: pixiv_tailor.GetTrainedModelsResponse
	(*SystemInfo)(nil),                 // 33: pixiv_tailor.SystemInfo
	(*MemoryInfo)(nil),                 // 34: pixiv_tailor.MemoryInfo
	(*CPUInfo)(nil),                    // 35: pixiv_tailor.CPUInfo
	(*DiskInfo)(nil),                   // 36: pixiv_tailor.DiskInfo
	(*GetSystemInfoRequest)(nil),       // 37: pixiv_tailor.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),      // 38: pixiv_tailor.GetSystemInfoResponse
}
var file_pixiv_tailor_proto_depIdxs = []int32{
	0,  // 0: pixiv_tailor.GetConfigResponse.status:type_name -> pixiv_tailor.Status
	2,  // 1: pixiv_tailor.GetConfigResponse.config:type_name -> pixiv_tailor.ConfigModule
	0,  // 2: pixiv_tailor.UpdateConfigResponse.status:type_name -> pixiv_tailor.Status
	0,  // 3: pixiv_tailor.ExportConfigResponse.status:type_name -> pixiv_tailor.Status
	0,  // 4: pixiv_tailor.ImportConfigResponse.status:type_name -> pixiv_tailor.Status
	0,  // 5: pixiv_tailor.CreateTaskResponse.status:type_name -> pixiv_tailor.Status
	11, // 6: pixiv_tailor.CreateTaskResponse.task:type_name -> pixiv_tailor.Task
	0,  // 7: pixiv_tailor.GetTaskStatusResponse.status:type_name -> pixiv_tailor.Status
	11, // 8: pixiv_tailor.GetTaskStatusResponse.task:type_name -> pixiv_tailor.Task
	1,  // 9: pixiv_tailor.ListTasksRequest.pagination:type_name -> pixiv_tailor.Pagination
	0,  // 10: pixiv_tailor.ListTasksResponse.status:type_name -> pixiv_tailor.Status
	11, // 11: pixiv_tailor.ListTasksResponse.tasks:type_name -> pixiv_tailor.Task
	1,  // 12: pixiv_tailor.ListTasksResponse.pagination:type_name -> pixiv_tailor.Pagination
	0,  // 13: pixiv_tailor.CancelTaskResponse.status:type_name -> pixiv_tailor.Status
	1,  // 14: pixiv_tailor.GetCrawlResultsRequest.pagination:type_name -> pixiv_tailor.Pagination
	0,  // 15: pixiv_tailor.GetCrawlResultsResponse.status:type_name -> pixiv_tailor.Status
	24, // 16: pixiv_tailor.GetCrawlResultsResponse.results:type_name -> pixiv_tailor.CrawlResult
	1,  // 17: pixiv_tailor.GetCrawlResultsResponse.pagination:type_name -> pixiv_tailor.Pagination
	1,  // 18: pixiv_tailor.GetGeneratedImagesRequest.pagination:type_name -> pixiv_tailor.Pagination
	0,  // 19: pixiv_tailor.GetGeneratedImagesResponse.status:type_name -> pixiv_tailor.Status
	27, // 20: pixiv_tailor.GetGeneratedImagesResponse.images:type_name -> pixiv_tailor.GeneratedImage
	1,  // 21: pixiv_tailor.GetGeneratedImagesResponse.pagination:type_name -> pixiv_tailor.Pagination
	1,  // 22: pixiv_tailor.GetTrainedModelsRequest.pagination:type_name -> pixiv_tailor.Pagination
	0,  // 23: pixiv_tailor.GetTrainedModelsResponse.status:type_name -> pixiv_tailor.Status
	30, // 24: pixiv_tailor.GetTrainedModelsResponse.models:type_name -> pixiv_tailor.TrainedModel
	1,  // 25: pixiv_tailor.GetTrainedModelsResponse.pagination:type_name -> pixiv_tailor.Pagination
	34, // 26: pixiv_tailor.SystemInfo.memory:type_name -> pixiv_tailor.MemoryInfo
	35, // 27: pixiv_tailor.SystemInfo.cpu:type_name -> pixiv_tailor.CPUInfo
	36, // 28: pixiv_tailor.SystemInfo.disk:type_name -> pixiv_tailor.DiskInfo
	0,  // 29: pixiv_tailor.GetSystemInfoResponse.status:type_name -> pixiv_tailor.Status
	33, // 30: pixiv_tailor.GetSystemInfoResponse.system_info:type_name -> pixiv_tailor.SystemInfo
	3,  // 31: pixiv_tailor.PixivTailorService.GetConfig:input_type -> pixiv_tailor.GetConfigRequest
	5,  // 32: pixiv_tailor.PixivTailorService.UpdateConfig:input_type -> pixiv_tailor.UpdateConfigRequest
	7,  // 33: pixiv_tailor.PixivTailorService.ExportConfig:input_type -> pixiv_tailor.ExportConfigRequest
	9,  // 34: pixiv_tailor.PixivTailorService.ImportConfig:input_type -> pixiv_tailor.ImportConfigRequest
	12, // 35: pixiv_tailor.PixivTailorService.CreateTask:input_type -> pixiv_tailor.CreateTaskRequest
	14, // 36: pixiv_tailor.PixivTailorService.GetTaskStatus:input_type -> pixiv_tailor.GetTaskStatusRequest
	16, // 37: pixiv_tailor.PixivTailorService.ListTasks:input_type -> pixiv_tailor.ListTasksRequest
	18, // 38: pixiv_tailor.PixivTailorService.CancelTask:input_type -> pixiv_tailor.CancelTaskRequest
	21, // 39: pixiv_tailor.PixivTailorService.GetTaskProgress:input_type -> pixiv_tailor.GetTaskProgressRequest
	23, // 40: pixiv_tailor.PixivTailorService.GetTaskLogs:input_type -> pixiv_tailor.GetTaskLogsRequest
	25, // 41: pixiv_tailor.PixivTailorService.GetCrawlResults:input_type -> pixiv_tailor.GetCrawlResultsRequest
	28, // 42: pixiv_tailor.PixivTailorService.GetGeneratedImages:input_type -> pixiv_tailor.GetGeneratedImagesRequest
	31, // 43: pixiv_tailor.PixivTailorService.GetTrainedModels:input_type -> pixiv_tailor.GetTrainedModelsRequest
	37, // 44: pixiv_tailor.PixivTailorService.GetSystemInfo:input_type -> pixiv_tailor.GetSystemInfoRequest
	4,  // 45: pixiv_tailor.PixivTailorService.GetConfig:output_type -> pixiv_tailor.GetConfigResponse
	6,  // 46: pixiv_tailor.PixivTailorService.UpdateConfig:output_type -> pixiv_tailor.UpdateConfigResponse
	8,  // 47: pixiv_tailor.PixivTailorService.ExportConfig:output_type -> pixiv_tailor.ExportConfigResponse
	10, // 48: pixiv_tailor.PixivTailorService.ImportConfig:output_type -> pixiv_tailor.ImportConfigResponse
	13, // 49: pixiv_tailor.PixivTailorService.CreateTask:output_type -> pixiv_tailor.CreateTaskResponse
	15, // 50: pixiv_tailor.PixivTailorService.GetTaskStatus:output_type -> pixiv_tailor.GetTaskStatusResponse
	17, // 51: pixiv_tailor.PixivTailorService.ListTasks:output_type -> pixiv_tailor.ListTasksResponse
	19, // 52: pixiv_tailor.PixivTailorService.CancelTask:output_type -> pixiv_tailor.CancelTaskResponse
	20, // 53: pixiv_tailor.PixivTailorService.GetTaskProgress:output_type -> pixiv_tailor.TaskProgressUpdate
	22, // 54: pixiv_tailor.PixivTailorService.GetTaskLogs:output_type -> pixiv_tailor.LogEntry
	26, // 55: pixiv_tailor.PixivTailorService.GetCrawlResults:output_type -> pixiv_tailor.GetCrawlResultsResponse
	29, // 56: pixiv_tailor.PixivTailorService.GetGeneratedImages:output_type -> pixiv_tailor.GetGeneratedImagesResponse
	32, // 57: pixiv_tailor.PixivTailorService.GetTrainedModels:output_type -> pixiv_tailor.GetTrainedModelsResponse
	38, // 58: pixiv_tailor.PixivTailorService.GetSystemInfo:output_type -> pixiv_tailor.GetSystemInfoResponse
	45, // [45:59] is the sub-list for method output_type
	31, // [31:45] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_pixiv_tailor_proto_init() }
func file_pixiv_tailor_proto_init() {
	if File_pixiv_tailor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pixiv_tailor_proto_rawDesc), len(file_pixiv_tailor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pixiv_tailor_proto_goTypes,
		DependencyIndexes: file_pixiv_tailor_proto_depIdxs,
		MessageInfos:      file_pixiv_tailor_proto_msgTypes,
	}.Build()
	File_pixiv_tailor_proto = out.File
	file_pixiv_tailor_proto_goTypes = nil
	file_pixiv_tailor_proto_depIdxs = nil
}
